# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(646, 550)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 380, 101, 41))
        self.pushButton.setStyleSheet("\n"
"background-color: rgb(70, 255, 184);\n"
"border - radius: 5px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(240, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.result = QtWidgets.QLabel(Dialog)
        self.result.setGeometry(QtCore.QRect(240, 210, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.cb_num = QtWidgets.QCheckBox(Dialog)
        self.cb_num.setGeometry(QtCore.QRect(239, 280, 141, 21))
        self.cb_num.setObjectName("cb_num")
        self.cb_leter = QtWidgets.QCheckBox(Dialog)
        self.cb_leter.setGeometry(QtCore.QRect(240, 310, 171, 17))
        self.cb_leter.setObjectName("cb_leter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Згенерувати"))
        self.title.setText(_translate("Dialog", "Генератор паролів"))
        self.result.setText(_translate("Dialog", "Тут буде результат"))
        self.cb_num.setText(_translate("Dialog", "Використовувати числа"))
        self.cb_leter.setText(_translate("Dialog", "Використовувати альфавіт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
